function [trialsNames, trialsMatrix]=Continuous_Phase(S,PhaseName)

switch PhaseName
	case 'Reward only' 
        trialsNames={'Uncued Reward','blank',...
            'blank','blank',...
            'blank','blank'};
        trialsMatrix=[...
        %  1.type, 2.proba, 3.sound, 4.delay,   5.valve,                6.Outcome         	7.Marker
            1,   1,         0,      S.GUI.Delay,   S.GUI.RewardValve,      S.InterRew,         double('o');...   
            2,   0,         1,      S.GUI.Delay,   S.GUI.OmissionValve,    S.InterRew,         double('s');...   
            3,   0,         2,      S.GUI.Delay,   S.GUI.PunishValve,      S.GUI.PunishTime,   double('d');...   
            4,   0,         2,      S.GUI.Delay,   S.GUI.OmissionValve,    S.InterRew,         double('s');...    
            5,   0,         0,      S.GUI.Delay,   S.GUI.RewardValve,      S.InterRew,         double('o');...    
            6,   0,         0,      S.GUI.Delay,   S.GUI.PunishValve,      S.GUI.PunishTime,   double('d')];
        	
    case 'RewardAndCue' 
        trialsNames={'Uncued Reward','Cue Reward',...
            'blank','blank',...
            'blank','blank'};
        trialsMatrix=[...
        %  1.type, 2.proba, 3.sound, 4.delay,   5.valve,                6.Outcome         	7.Marker
            1,   0.5,       0,      S.GUI.Delay,   S.GUI.RewardValve,      S.InterRew,         double('o');...   
            2,   0.5,       1,      S.GUI.Delay,   S.GUI.OmissioValve,    S.InterRew,         double('s');...   
            3,   0,         2,      S.GUI.Delay,   S.GUI.PunishValve,      S.GUI.PunishTime,   double('d');...   
            4,   0,         2,      S.GUI.Delay,   S.GUI.OmissionValve,    S.InterRew,         double('s');...    
            5,   0,         0,      S.GUI.Delay,   S.GUI.RewardValve,      S.InterRew,         double('o');...    
            6,   0,         0,      S.GUI.Delay,   S.GUI.PunishValve,      S.GUI.PunishTime,   double('d')];
        
        case 'PunishAndCue' 
        trialsNames={'Uncued Punish','Cue',...
            'blank','blank',...
            'blank','blank'};
        trialsMatrix=[...
        %  1.type, 2.proba, 3.sound, 4.delay,   5.valve,                6.Outcome         	7.Marker
            1,   0.5,       0,      S.GUI.Delay,   S.GUI.PunishValve,      S.GUI.PunishTime,         double('o');...   
            2,   0.5,       4,      S.GUI.Delay,   S.GUI.Omissionalve,      S.InterRew,         double('s');...   
            3,   0,         2,      S.GUI.Delay,   S.GUI.PunishValve,      S.GUI.PunishTime,   double('d');...   
            4,   0,         2,      S.GUI.Delay,   S.GUI.OmissionValve,    S.InterRew,         double('s');...    
            5,   0,         0,      S.GUI.Delay,   S.GUI.RewardValve,      S.InterRew,         double('o');...    
            6,   0,         0,      S.GUI.Delay,   S.GUI.PunishValve,      S.GUI.PunishTime,   double('d')];    
        
end   
end
